INSERT INTO crypto_currencies (symbol, name, currency) VALUES
('BTC', 'Bitcoin', 'USD'),
('ETH', 'Ethereum', 'USD'),
('USDT', 'Tether', 'USD'),
('BNB', 'Binance Coin', 'USD'),
('USDC', 'USD Coin', 'USD'),
('XRP', 'Ripple', 'USD'),
('ADA', 'Cardano', 'USD'),
('SOL', 'Solana', 'USD'),
('DOGE', 'Dogecoin', 'USD'),
('DOT', 'Polkadot', 'USD'),
('LTC', 'Litecoin', 'USD'),
('AVAX', 'Avalanche', 'USD'),
('SHIB', 'Shiba Inu', 'USD'),
('TRX', 'TRON', 'USD'),
('UNI', 'Uniswap', 'USD'),
('LINK', 'Chainlink', 'USD'),
('ATOM', 'Cosmos', 'USD'),
('XLM', 'Stellar', 'USD'),
('ALGO', 'Algorand', 'USD'),
('MATIC', 'Polygon', 'USD');